[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
extra-index-url = https://mirror.sjtu.edu.cn/pytorch-wheels/cu121
trusted-host = pypi.tuna.tsinghua.edu.cn
               mirror.sjtu.edu.cn
timeout = 120

